title: biggates 难得更新的小站

timezone: Asia/Shanghai

highlighter: pygments

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - no intra_emphasis
    - strikethrough
    - autolink
    - tables
  
encoding: utf-8